# Generated by Django 4.2.4 on 2023-08-16 22:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('release_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goldsplit_api.games')),
            ],
        ),
        migrations.CreateModel(
            name='Splits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('time', models.PositiveBigIntegerField()),
                ('total_time', models.PositiveBigIntegerField()),
                ('gold_time', models.PositiveBigIntegerField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldsplit_api.runs')),
            ],
        ),
    ]
