# Generated by Django 4.2.4 on 2023-08-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsplit_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='release_year',
            field=models.IntegerField(),
        ),
    ]
