# Generated by Django 4.2.4 on 2023-08-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsplit_api', '0002_alter_games_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='splits',
            name='average_time',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='splits',
            name='gold_total_time',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
