# Generated by Django 4.2.4 on 2023-08-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsplit_api', '0003_splits_average_time_splits_gold_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='release_year',
            field=models.IntegerField(null=True),
        ),
    ]
