# Generated by Django 4.2.4 on 2023-08-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsplit_api', '0004_alter_games_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
