# Generated by Django 4.2.4 on 2023-08-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsplit_api', '0005_alter_games_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='splits',
            name='average_total_time',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
