# Generated by Django 4.2.4 on 2023-08-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsplit_api', '0006_splits_average_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='time',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
