# Generated by Django 4.2.4 on 2023-08-19 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsplit_api', '0007_runs_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='splits',
            name='reset_percentage',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(100)),
            preserve_default=False,
        ),
    ]
