# Generated by Django 4.2.4 on 2023-08-23 20:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goldsplit_api', '0008_runs_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='runs',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 20, 36, 28, 33831), editable=False),
        ),
    ]
